# Generated by Django 5.2.7 on 2026-01-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=989, max_digits=10),
            preserve_default=False,
        ),
    ]
