# Generated by Django 5.2.7 on 2026-01-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_orderitem_price_currency_orderitem_price_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_per_unit',
            new_name='total_price',
        ),
    ]
