# Generated by Django 5.2.7 on 2026-01-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
