# Generated by Django 5.2.7 on 2026-01-20 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_alter_infrastructurecredential_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=128)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.merchant')),
            ],
        ),
    ]
