# Generated by Django 5.2.7 on 2026-01-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_infrastructurecredential_options_and_more'),
        ('bonus', '0002_bonuscategory_created_at_bonuscategory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
