# Generated by Django 5.2.7 on 2026-01-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_infrastructurecredential_options_and_more'),
        ('bonus', '0003_userblock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together={('merchant', 'username')},
        ),
    ]
