# Generated by Django 5.2.7 on 2026-01-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_alter_userblock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
