# Generated by Django 5.2.7 on 2025-10-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchant_infrastructurecredentials_user_merchant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfrastructureCredentials',
            new_name='InfrastructureCredential',
        ),
    ]
