# Generated by Django 5.2.7 on 2025-12-26 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_insitenotification_insitenotificationuserinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insitenotificationuserinteraction',
            old_name='is_deleted_by_admin',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='insitenotification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('user_specific', 'User Specific')], default='general', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insitenotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
