# Generated by Django 5.2.7 on 2025-12-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_is_deleted_by_admin_insitenotificationuserinteraction_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insitenotificationuserinteraction',
            name='body',
        ),
        migrations.RemoveField(
            model_name='insitenotificationuserinteraction',
            name='end_showing_at',
        ),
        migrations.RemoveField(
            model_name='insitenotificationuserinteraction',
            name='start_showing_at',
        ),
        migrations.RemoveField(
            model_name='insitenotificationuserinteraction',
            name='subject',
        ),
    ]
