# Generated by Django 5.2.7 on 2025-12-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_insitenotificationuserinteraction_body_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insitenotificationuserinteraction',
            unique_together={('notification', 'user')},
        ),
    ]
