# Generated by Django 5.2.7 on 2025-12-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_insitenotificationuserinteraction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insitenotification',
            name='type',
            field=models.CharField(choices=[('general', 'Genel'), ('user_specific', 'Kullanıcıya Özel')], max_length=40),
        ),
    ]
