# Generated by Django 5.2.7 on 2026-01-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_insitenotification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='currency',
        ),
    ]
