# Generated by Django 5.2.7 on 2026-01-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_merchant_currency'),
        ('commerce', '0008_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='commerce.currency'),
            preserve_default=False,
        ),
    ]
