# Generated by Django 5.2.7 on 2026-01-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merchant_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['-created_at']},
        ),
    ]
