# Generated by Django 5.2.7 on 2026-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_merchant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructurecredential',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='infrastructurecredential',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
