# Generated by Django 5.2.7 on 2025-12-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faqtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
